language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install
  - git clone git://github.com/squizlabs/PHP_CodeSniffer.git sniffer

script:
  - php sniffer/scripts/phpcs --standard=psr2 src/
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm